[package]
name = "rregex"
version = "0.1.0"
edition = "2024"

[lib]
name = "rregex"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
pprof = { version = "0.15", features = ["flamegraph"] }

[[bench]]
name = "match_bench"
harness = false